# Generated by Django 4.2.7 on 2023-11-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
    ]
