# Generated by Django 4.2.7 on 2023-12-11 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_watchlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlistitems",
            name="watchlist",
        ),
    ]
