# Generated by Django 4.2.7 on 2023-11-30 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_watchlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlistgroup",
            name="watchlist_items",
        ),
    ]
