# Generated by Django 4.2.7 on 2023-11-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
        ("stock_watchlist", "0002_remove_watchlistgroup_watchlist_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlistitem",
            name="group",
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_items",
                to="user_profile.userprofile",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="watchlistitem",
            name="group",
            field=models.ManyToManyField(
                related_name="watchlist_items",
                to="stock_watchlist.watchlistgroup",
                verbose_name="Group",
            ),
        ),
    ]
