# Generated by Django 4.2.7 on 2023-12-12 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_watchlist", "0002_remove_watchlistitems_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlistitems",
            name="group",
        ),
        migrations.DeleteModel(
            name="WatchListGroup",
        ),
    ]
