# Generated by Django 4.2.7 on 2024-01-09 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import stock_watchlist.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
        ("stock_watchlist", "0004_watchlistitems_transactiontype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sector", models.CharField(max_length=100)),
                (
                    "trade_date",
                    models.DateTimeField(
                        default=stock_watchlist.models.default_trade_date
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("comments", models.CharField(blank=True, max_length=140)),
                (
                    "transactionType",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.DeleteModel(
            name="WatchListItems",
        ),
    ]
