# Generated by Django 4.2.7 on 2023-11-30 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import stock_watchlist_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0002_alter_userprofile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchListGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Name")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist Group",
                "verbose_name_plural": "Watchlist Groups",
            },
        ),
        migrations.CreateModel(
            name="WatchListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                ("sector", models.CharField(max_length=100)),
                (
                    "trade_date",
                    models.DateTimeField(
                        default=stock_watchlist_app.models.default_date,
                        verbose_name="Trade Date",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        default=datetime.datetime.utcnow,
                        verbose_name="Created Timestamp",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        max_length=140, null=True, verbose_name="Comments"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_watchlist_app.watchlistgroup",
                        verbose_name="Group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist Item",
                "verbose_name_plural": "Watchlist Items",
            },
        ),
    ]
