# Generated by Django 4.2.7 on 2024-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptotransaction",
            name="fees",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
